# Generated by Django 4.1.6 on 2023-10-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
