# Generated by Django 4.1.6 on 2023-10-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_product_payment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='', max_length=100),
        ),
    ]
