# Generated by Django 4.1.6 on 2023-10-31 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
