# Generated by Django 4.1.6 on 2023-03-07 19:42

import city.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_city_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=city.models.get_image_path),
        ),
    ]
