name: middleware-information
dependencies:
  - python=3.10.9
  - pip=23.2.1
  - pip:
    # ASGI interface between your code and the server
    - asgiref==3.6.0

    # AWS SDK for Python
    - boto3==1.26.64
    - botocore==1.29.84

    # A library for caching
    - cachetools==5.3.1

    # Character encoding auto-detection
    - charset-normalizer==3.0.1

    # Core API library
    - coreapi==2.3.3
    - coreschema==0.0.4

    # Database configuration for Django
    - dj-database-url==1.2.0

    # High-level web framework for Python
    - Django==4.1.6

    # Handling CORS headers for Django
    - django-cors-headers==3.13.0

    # Provides country data for Django
    - django-countries-plus==2.1.0

    # Environment variable handler for Django
    - django-dotenv==1.4.2

    # Filtering support for Django and DRF
    - django-filter==22.1
    - django-storages==1.13.2

    # Web API framework based on Django
    - djangorestframework==3.14.0
    - djangorestframework-simplejwt==5.2.2

    # Swagger generator for DRF
    - drf-yasg==1.21.4

    # Google API core libraries
    - google-api-core==2.11.1
    - google-auth==2.22.0
    - google-cloud-core==2.3.3
    - google-cloud-translate==3.11.2
    - google-cloud-vision==3.4.4
    - googleapis-common-protos==1.59.1

    # gRPC for Python
    - grpcio==1.56.0
    - grpcio-status==1.56.0

    # WSGI HTTP Server
    - gunicorn==20.1.0

    # Domain name handling
    - idna==3.4

    # Pluralization and singularization of English nouns
    - inflection==0.5.1

    # Types for core API libraries
    - itypes==1.2.0

    # Templating engine
    - Jinja2==3.1.2

    # JSON path expressions for Python
    - jmespath==1.0.1

    # Markdown processing
    - Markdown==3.4.1

    # XML and HTML escaping
    - MarkupSafe==2.1.2

    # Packaging utilities
    - packaging==23.0

    # Image processing
    - Pillow==9.4.0

    # Protobuf handling
    - proto-plus==1.22.3
    - protobuf==4.23.4

    # PostgreSQL adapter
    - psycopg2-binary==2.9.5

    # ASN.1 for Python
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0

    # Country data
    - pycountry==22.3.5

    # JSON Web Token
    - PyJWT==2.6.0

    # Date and time utilities
    - python-dateutil==2.8.2

    # Environment variable loader
    - python-dotenv==1.0.0

    # Timezone definitions
    - pytz==2022.7.1

    # HTTP client
    - requests==2.28.2

    # RSA cryptography
    - rsa==4.9

    # YAML parser and emitter
    - ruamel.yaml==0.17.21
    - ruamel.yaml.clib==0.2.7

    # Amazon S3 Transfer Manager
    - s3transfer==0.6.0

    # Python 2 and 3 compatibility
    - six==1.16.0

    # SQL parsing
    - sqlparse==0.4.3

    # URI templates
    - uritemplate==4.1.1

    # Another HTTP client
    - urllib3==1.26.14

    # Static file serving for web apps
    - whitenoise==6.3.0
