# Generated by Django 4.1.6 on 2023-03-11 19:37

from django.db import migrations, models
import permit.models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0002_alter_permit_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=permit.models.get_image_path),
        ),
    ]
