# Generated by Django 4.1.6 on 2023-03-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0003_permit_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='title',
            field=models.CharField(default='Permit process and requirements', max_length=200),
        ),
    ]
