# Generated by Django 4.1.6 on 2023-03-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0004_alter_permit_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='description',
            field=models.CharField(default='Permit process and requirements', max_length=200),
        ),
        migrations.AlterField(
            model_name='permit',
            name='title',
            field=models.CharField(default='Permit', max_length=200),
        ),
    ]
