# Generated by Django 4.1.6 on 2023-03-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0005_permit_description_alter_permit_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='descriptionEs',
            field=models.CharField(default='Proceso y requisitos del permiso de residencia', max_length=200),
        ),
        migrations.AddField(
            model_name='permit',
            name='descriptionFr',
            field=models.CharField(default='Processus et exigences de permis de séjour', max_length=200),
        ),
        migrations.AddField(
            model_name='permit',
            name='descriptionGe',
            field=models.CharField(default='Verfahren und Anforderungen für die Aufenthaltserlaubnis', max_length=200),
        ),
        migrations.AddField(
            model_name='permit',
            name='descriptionGr',
            field=models.CharField(default='Διαδικασία και απαιτήσεις άδειας διαμονής', max_length=200),
        ),
        migrations.AddField(
            model_name='permit',
            name='descriptionIt',
            field=models.CharField(default='Processo e requisiti del permesso di soggiorno', max_length=200),
        ),
        migrations.AddField(
            model_name='permit',
            name='titleEs',
            field=models.CharField(default='Permiso de residencia', max_length=200),
        ),
        migrations.AddField(
            model_name='permit',
            name='titleFr',
            field=models.CharField(default='Permis de séjour', max_length=200),
        ),
        migrations.AddField(
            model_name='permit',
            name='titleGe',
            field=models.CharField(default='Aufenthaltserlaubnis', max_length=200),
        ),
        migrations.AddField(
            model_name='permit',
            name='titleGr',
            field=models.CharField(default='Άδεια διαμονής', max_length=200),
        ),
        migrations.AddField(
            model_name='permit',
            name='titleIt',
            field=models.CharField(default='Permesso di soggiorno', max_length=200),
        ),
        migrations.AlterField(
            model_name='permit',
            name='title',
            field=models.CharField(default='Residence Permit', max_length=200),
        ),
    ]
