# Generated by Django 4.1.6 on 2023-07-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
