# Generated by Django 4.1.6 on 2023-07-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_bookmark_uniquetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='uniqueTitle',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
