# Generated by Django 4.1.6 on 2024-02-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_bookmark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='table_image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
