CANTON_CHOICES = (
    ('AG', 'Aargau'),
    ('AR', 'Appenzell Ausserrhoden'),
    ('AI', 'Appenzell Innerrhoden'),
    ('BL', 'Basel-Landschaft'),
    ('BS', 'Basel-Stadt'),
    ('BE', 'Bern'),
    ('FR', 'Fribourg'),
    ('GE', 'Geneva'),
    ('GL', 'Glarus'),
    ('GR', 'Graubünden'),
    ('JU', 'Jura'),
    ('LU', 'Lucerne'),
    ('NE', 'Neuchâtel'),
    ('NW', 'Nidwalden'),
    ('OW', 'Obwalden'),
    ('SG', 'St. Gallen'),
    ('SH', 'Schaffhausen'),
    ('SZ', 'Schwyz'),
    ('SO', 'Solothurn'),
    ('TG', 'Thurgau'),
    ('TI', 'Ticino'),
    ('UR', 'Uri'),
    ('VS', 'Valais'),
    ('VD', 'Vaud'),
    ('ZG', 'Zug'),
    ('ZH', 'Zurich'),
)
