COUNTRY_LANGUAGES = [
    {'country': 'Afghanistan', 'language': 'Pashto, Dari'},
    {'country': 'Albania', 'language': 'Albanian'},
    {'country': 'Algeria', 'language': 'Arabic'},
    {'country': 'Andorra', 'language': 'Catalan'},
    {'country': 'Angola', 'language': 'Portuguese'},
    {'country': 'Antigua and Barbuda', 'language': 'English'},
    {'country': 'Argentina', 'language': 'Spanish'},
    {'country': 'Armenia', 'language': 'Armenian'},
    {'country': 'Australia', 'language': 'English'},
    {'country': 'Austria', 'language': 'German'},
    {'country': 'Azerbaijan', 'language': 'Azerbaijani'},
    {'country': 'Bahamas', 'language': 'English'},
    {'country': 'Bahrain', 'language': 'Arabic'},
    {'country': 'Bangladesh', 'language': 'Bengali'},
    {'country': 'Barbados', 'language': 'English'},
    {'country': 'Belarus', 'language': 'Belarusian, Russian'},
    {'country': 'Belgium', 'language': 'Dutch, French, German'},
    {'country': 'Belize', 'language': 'English'},
    {'country': 'Benin', 'language': 'French'},
    {'country': 'Bhutan', 'language': 'Dzongkha'},
    {'country': 'Bolivia', 'language': 'Spanish'},
    {'country': 'Bosnia and Herzegovina', 'language': 'Bosnian, Croatian, Serbian'},
    {'country': 'Botswana', 'language': 'English'},
    {'country': 'Brazil', 'language': 'Portuguese'},
    {'country': 'Brunei', 'language': 'Malay'},
    {'country': 'Bulgaria', 'language': 'Bulgarian'},
    {'country': 'Burkina Faso', 'language': 'French'},
    {'country': 'Burundi', 'language': 'Kirundi, French'},
    {'country': 'Cambodia', 'language': 'Khmer'},
    {'country': 'Cameroon', 'language': 'English, French'},
    {'country': 'Canada', 'language': 'English, French'},
    {'country': 'Cape Verde', 'language': 'Portuguese'},
    {'country': 'Central African Republic', 'language': 'French, Sango'},
    {'country': 'Chad', 'language': 'Arabic, French'},
    {'country': 'Chile', 'language': 'Spanish'},
    {'country': 'China', 'language': 'Chinese'},
    {'country': 'Colombia', 'language': 'Spanish'},
    {'country': 'Comoros', 'language': 'Arabic, French, Comorian'},
    {'country': 'Congo', 'language': 'French, Lingala'},
    {'country': 'Costa Rica', 'language': 'Spanish'},
    {'country': 'Croatia', 'language': 'Croatian'},
    {'country': 'Cuba', 'language': 'Spanish'},
    {'country': 'Cyprus', 'language': 'Greek, Turkish'},
    {'country': 'Czech Republic', 'language': 'Czech'},
    {'country': 'Denmark', 'language': 'Danish'},
    {'country': 'Djibouti', 'language': 'Arabic, French'},
    {'country': 'Dominica', 'language': 'English'},
    {'country': 'Dominican Republic', 'language': 'Spanish'},
    {'country': 'East Timor', 'language': 'Tetum, Portuguese'},
    {'country': 'Ecuador', 'language': 'Spanish'},
    {'country': 'Egypt', 'language': 'Arabic'},
    {'country': 'El Salvador', 'language': 'Spanish'},
    {'country': 'Equatorial Guinea', 'language': 'Spanish, French, Portuguese'},
    {'country': 'Eritrea', 'language': 'Tigrinya, Arabic, English'},
    {'country': 'Estonia', 'language': 'Estonian'},
    {'country': 'Ethiopia', 'language': 'Amharic'},
    {'country': 'Fiji', 'language': 'English, Fijian, Hindi'},
    {'country': 'Finland', 'language': 'Finnish, Swedish'},
    {'country': 'France', 'language': 'French'},
    {'country': 'Gabon', 'language': 'French'},
    {'country': 'Gambia', 'language': 'English'},
    {'country': 'Georgia', 'language': 'Georgian'},
    {'country': 'Germany', 'language': 'German'},
    {'country': 'Ghana', 'language': 'English'},
    {'country': 'Greece', 'language': 'Greek'},
    {'country': 'Grenada', 'language': 'English'},
    {'country': 'Guatemala', 'language': 'Spanish'},
    {'country': 'Guinea', 'language': 'French'},
    {'country': 'Guinea-Bissau', 'language': 'Portuguese'},
    {'country': 'Guyana', 'language': 'English'},
    {'country': 'Haiti', 'language': 'French, Haitian Creole'},
    {'country': 'Honduras', 'language': 'Spanish'},
    {'country': 'Hungary', 'language': 'Hungarian'},
    {'country': 'Iceland', 'language': 'Icelandic'},
    {'country': 'India', 'language': 'Hindi, English'},
    {'country': 'Indonesia', 'language': 'Indonesian'},
    {'country': 'Iran', 'language': 'Persian'},
    {'country': 'Iraq', 'language': 'Arabic, Kurdish'},
    {'country': 'Ireland', 'language': 'English, Irish'},
    {'country': 'Israel', 'language': 'Hebrew, Arabic'},
    {'country': 'Italy', 'language': 'Italian'},
    {'country': 'Jamaica', 'language': 'English'},
    {'country': 'Japan', 'language': 'Japanese'},
    {'country': 'Jordan', 'language': 'Arabic'},
    {'country': 'Kazakhstan', 'language': 'Kazakh, Russian'},
    {'country': 'Kenya', 'language': 'Swahili, English'},
    {'country': 'Kiribati', 'language': 'English, Kiribati'},
    {'country': 'Korea, North', 'language': 'Korean'},
    {'country': 'Korea, South', 'language': 'Korean'},
    {'country': 'Kosovo', 'language': 'Albanian, Serbian'},
    {'country': 'Kuwait', 'language': 'Arabic'},
    {'country': 'Kyrgyzstan', 'language': 'Kyrgyz, Russian'},
    {'country': 'Laos', 'language': 'Lao'},
    {'country': 'Latvia', 'language': 'Latvian'},
    {'country': 'Lebanon', 'language': 'Arabic'},
    {'country': 'Lesotho', 'language': 'Sesotho, English'},
    {'country': 'Liberia', 'language': 'English'},
    {'country': 'Libya', 'language': 'Arabic'},
    {'country': 'Liechtenstein', 'language': 'German'},
    {'country': 'Lithuania', 'language': 'Lithuanian'},
    {'country': 'Luxembourg', 'language': 'Luxembourgish, French, German'},
    {'country': 'Macedonia', 'language': 'Macedonian'},
    {'country': 'Madagascar', 'language': 'Malagasy, French'},
    {'country': 'Malawi', 'language': 'Chichewa, English'},
    {'country': 'Malaysia', 'language': 'Malay'},
    {'country': 'Maldives', 'language': 'Dhivehi'},
    {'country': 'Mali', 'language': 'French'},
    {'country': 'Malta', 'language': 'Maltese, English'},
    {'country': 'Marshall Islands', 'language': 'Marshallese, English'},
    {'country': 'Mauritania', 'language': 'Arabic'},
    {'country': 'Mauritius', 'language': 'English'},
    {'country': 'Mexico', 'language': 'Spanish'},
    {'country': 'Micronesia', 'language': 'English'},
    {'country': 'Moldova', 'language': 'Moldavian, Romanian, Russian'},
    {'country': 'Monaco', 'language': 'French'},
    {'country': 'Mongolia', 'language': 'Mongolian'},
    {'country': 'Montenegro', 'language': 'Serbian, Montenegrin'},
    {'country': 'Morocco', 'language': 'Arabic, Berber'},
    {'country': 'Mozambique', 'language': 'Portuguese'},
    {'country': 'Myanmar', 'language': 'Burmese'},
    {'country': 'Namibia', 'language': 'English'},
    {'country': 'Nauru', 'language': 'Nauruan, English'},
    {'country': 'Nepal', 'language': 'Nepali'},
    {'country': 'Netherlands', 'language': 'Dutch'},
    {'country': 'New Zealand', 'language': 'English, Maori'},
    {'country': 'Nicaragua', 'language': 'Spanish'},
    {'country': 'Niger', 'language': 'French'},
    {'country': 'Nigeria', 'language': 'English'},
    {'country': 'Norway', 'language': 'Norwegian'},
    {'country': 'Oman', 'language': 'Arabic'},
    {'country': 'Pakistan', 'language': 'Urdu, English'},
    {'country': 'Palau', 'language': 'English, Palauan'},
    {'country': 'Panama', 'language': 'Spanish'},
    {'country': 'Papua New Guinea', 'language': 'English'},
    {'country': 'Paraguay', 'language': 'Spanish, Guarani'},
    {'country': 'Peru', 'language': 'Spanish'},
    {'country': 'Philippines', 'language': 'Filipino, English'},
    {'country': 'Poland', 'language': 'Polish'},
    {'country': 'Portugal', 'language': 'Portuguese'},
    {'country': 'Qatar', 'language': 'Arabic'},
    {'country': 'Romania', 'language': 'Romanian'},
    {'country': 'Russia', 'language': 'Russian'},
    {'country': 'Rwanda', 'language': 'Kinyarwanda, French, English'},
    {'country': 'Saint Kitts and Nevis', 'language': 'English'},
    {'country': 'Saint Lucia', 'language': 'English'},
    {'country': 'Saint Vincent and the Grenadines', 'language': 'English'},
    {'country': 'Samoa', 'language': 'Samoan, English'},
    {'country': 'San Marino', 'language': 'Italian'},
    {'country': 'Sao Tome and Principe', 'language': 'Portuguese'},
    {'country': 'Saudi Arabia', 'language': 'Arabic'},
    {'country': 'Senegal', 'language': 'French'},
    {'country': 'Serbia', 'language': 'Serbian'},
    {'country': 'Seychelles', 'language': 'Seselwa, English, French'},
    {'country': 'Sierra Leone', 'language': 'English'},
    {'country': 'Singapore', 'language': 'English, Malay, Mandarin, Tamil'},
    {'country': 'Slovakia', 'language': 'Slovak'},
    {'country': 'Slovenia', 'language': 'Slovene'},
    {'country': 'Solomon Islands', 'language': 'English'},
    {'country': 'Somalia', 'language': 'Somali, Arabic'},
    {'country': 'South Africa', 'language': 'Afrikaans, English, Zulu'},
    {'country': 'South Sudan', 'language': 'English'},
    {'country': 'Spain', 'language': 'Spanish'},
    {'country': 'Sri Lanka', 'language': 'Sinhala, Tamil'},
    {'country': 'Sudan', 'language': 'Arabic, English'},
    {'country': 'Suriname', 'language': 'Dutch'},
    {'country': 'Swaziland', 'language': 'English, Swazi'},
    {'country': 'Sweden', 'language': 'Swedish'},
    {'country': 'Switzerland', 'language': 'German, French, Italian, Romansh'},
    {'country': 'Syria', 'language': 'Arabic'},
    {'country': 'Taiwan', 'language': 'Mandarin'},
    {'country': 'Tajikistan', 'language': 'Tajik'},
    {'country': 'Tanzania', 'language': 'Swahili, English'},
    {'country': 'Thailand', 'language': 'Thai'},
    {'country': 'Togo', 'language': 'French'},
    {'country': 'Tonga', 'language': 'Tongan, English'},
    {'country': 'Trinidad and Tobago', 'language': 'English'},
    {'country': 'Tunisia', 'language': 'Arabic'},
    {'country': 'Turkey', 'language': 'Turkish'},
    {'country': 'Turkmenistan', 'language': 'Turkmen'},
    {'country': 'Tuvalu', 'language': 'Tuvaluan, English'},
    {'country': 'Uganda', 'language': 'English, Swahili'},
    {'country': 'Ukraine', 'language': 'Ukrainian'},
    {'country': 'United Arab Emirates', 'language': 'Arabic'},
    {'country': 'United Kingdom', 'language': 'English'},
    {'country': 'United States', 'language': 'English'},
    {'country': 'Uruguay', 'language': 'Spanish'},
    {'country': 'Uzbekistan', 'language': 'Uzbek'},
    {'country': 'Vanuatu', 'language': 'Bislama, English, French'},
    {'country': 'Vatican City', 'language': 'Italian, Latin'},
    {'country': 'Venezuela', 'language': 'Spanish'},
    {'country': 'Vietnam', 'language': 'Vietnamese'},
    {'country': 'Yemen', 'language': 'Arabic'},
    {'country': 'Zambia', 'language': 'English'},
    {'country': 'Zimbabwe', 'language': 'English, Shona, Ndebele'}
]



