COUNTRY_LANGUAGES = [
    {'country': 'Afghanistan', 'language': 'ps'},
    {'country': 'Albania', 'language': 'sq'},
    {'country': 'Algeria', 'language': 'ar'},
    {'country': 'Andorra', 'language': 'ca'},
    {'country': 'Angola', 'language': 'pt'},
    {'country': 'Antigua and Barbuda', 'language': 'en'},
    {'country': 'Argentina', 'language': 'es'},
    {'country': 'Armenia', 'language': 'hy'},
    {'country': 'Australia', 'language': 'en'},
    {'country': 'Austria', 'language': 'de'},
    {'country': 'Azerbaijan', 'language': 'az'},
    {'country': 'Bahamas', 'language': 'en'},
    {'country': 'Bahrain', 'language': 'ar'},
    {'country': 'Bangladesh', 'language': 'bn'},
    {'country': 'Barbados', 'language': 'en'},
    {'country': 'Belarus', 'language': 'ru'},
    {'country': 'Belgium', 'language': 'de'},
    {'country': 'Belize', 'language': 'en'},
    {'country': 'Benin', 'language': 'fr'},
    {'country': 'Bhutan', 'language': 'dz'},
    {'country': 'Bolivia', 'language': 'es'},
    {'country': 'Bosnia and Herzegovina', 'language': 'sr'},
    {'country': 'Botswana', 'language': 'en'},
    {'country': 'Brazil', 'language': 'pt'},
    {'country': 'Brunei', 'language': 'ms'},
    {'country': 'Bulgaria', 'language': 'bg'},
    {'country': 'Burkina Faso', 'language': 'fr'},
    {'country': 'Burundi', 'language': 'fr'},
    {'country': 'Cambodia', 'language': 'km'},
    {'country': 'Cameroon', 'language': 'en'},
    {'country': 'Canada', 'language': 'en'},
    {'country': 'Cape Verde', 'language': 'pt'},
    {'country': 'Central African Republic', 'language': 'fr'},
    {'country': 'Chad', 'language': 'ar'},
    {'country': 'Chile', 'language': 'es'},
    {'country': 'China', 'language': 'zh'},
    {'country': 'Colombia', 'language': 'es'},
    {'country': 'Comoros', 'language': 'ar'},
    {'country': 'Congo', 'language': 'fr'},
    {'country': 'Costa Rica', 'language': 'es'},
    {'country': 'Croatia', 'language': 'hr'},
    {'country': 'Cuba', 'language': 'es'},
    {'country': 'Cyprus', 'language': 'el'},
    {'country': 'Czech Republic', 'language': 'cs'},
    {'country': 'Denmark', 'language': 'da'},
    {'country': 'Djibouti', 'language': 'ar'},
    {'country': 'Dominica', 'language': 'en'},
    {'country': 'Dominican Republic', 'language': 'es'},
    {'country': 'East Timor', 'language': 'pt'},
    {'country': 'Ecuador', 'language': 'es'},
    {'country': 'Egypt', 'language': 'ar'},
    {'country': 'El Salvador', 'language': 'es'},
    {'country': 'Equatorial Guinea', 'language': 'es'},
    {'country': 'Eritrea', 'language': 'ti'},
    {'country': 'Estonia', 'language': 'et'},
    {'country': 'Eswatini', 'language': 'en'},
    {'country': 'Ethiopia', 'language': 'am'},
    {'country': 'Fiji', 'language': 'en'},
    {'country': 'Finland', 'language': 'fi'},
    {'country': 'France', 'language': 'fr'},
    {'country': 'Gabon', 'language': 'fr'},
    {'country': 'Gambia', 'language': 'en'},
    {'country': 'Georgia', 'language': 'ka'},
    {'country': 'Germany', 'language': 'de'},
    {'country': 'Ghana', 'language': 'en'},
    {'country': 'Greece', 'language': 'el'},
    {'country': 'Grenada', 'language': 'en'},
    {'country': 'Guatemala', 'language': 'es'},
    {'country': 'Guinea', 'language': 'fr'},
    {'country': 'Guinea-Bissau', 'language': 'pt'},
    {'country': 'Guyana', 'language': 'en'},
    {'country': 'Haiti', 'language': 'ht'},
    {'country': 'Honduras', 'language': 'es'},
    {'country': 'Hungary', 'language': 'hu'},
    {'country': 'Iceland', 'language': 'is'},
    {'country': 'India', 'language': 'hi'},
    {'country': 'Indonesia', 'language': 'id'},
    {'country': 'Iran', 'language': 'fa'},
    {'country': 'Iraq', 'language': 'ar'},
    {'country': 'Ireland', 'language': 'en'},
    {'country': 'Israel', 'language': 'he'},
    {'country': 'Italy', 'language': 'it'},
    {'country': 'Jamaica', 'language': 'en'},
    {'country': 'Japan', 'language': 'ja'},
    {'country': 'Jordan', 'language': 'ar'},
    {'country': 'Kazakhstan', 'language': 'kk'},
    {'country': 'Kenya', 'language': 'sw'},
    {'country': 'Kiribati', 'language': 'en'},
    {'country': 'Korea, North', 'language': 'ko'},
    {'country': 'Korea, South', 'language': 'ko'},
    {'country': 'Kuwait', 'language': 'ar'},
    {'country': 'Kyrgyzstan', 'language': 'ky'},
    {'country': 'Laos', 'language': 'lo'},
    {'country': 'Latvia', 'language': 'lv'},
    {'country': 'Lebanon', 'language': 'ar'},
    {'country': 'Lesotho', 'language': 'en'},
    {'country': 'Liberia', 'language': 'en'},
    {'country': 'Libya', 'language': 'ar'},
    {'country': 'Liechtenstein', 'language': 'de'},
    {'country': 'Lithuania', 'language': 'lt'},
    {'country': 'Luxembourg', 'language': 'lb'},
    {'country': 'Madagascar', 'language': 'mg'},
    {'country': 'Malawi', 'language': 'ny'},
    {'country': 'Malaysia', 'language': 'ms'},
    {'country': 'Maldives', 'language': 'dv'},
    {'country': 'Mali', 'language': 'fr'},
    {'country': 'Malta', 'language': 'mt'},
    {'country': 'Marshall Islands', 'language': 'en'},
    {'country': 'Mauritania', 'language': 'ar'},
    {'country': 'Mauritius', 'language': 'en'},
    {'country': 'Mexico', 'language': 'es'},
    {'country': 'Micronesia', 'language': 'en'},
    {'country': 'Moldova', 'language': 'ro'},
    {'country': 'Monaco', 'language': 'fr'},
    {'country': 'Mongolia', 'language': 'mn'},
    {'country': 'Montenegro', 'language': 'sr'},
    {'country': 'Morocco', 'language': 'ar'},
    {'country': 'Mozambique', 'language': 'pt'},
    {'country': 'Myanmar', 'language': 'my'},
    {'country': 'Namibia', 'language': 'en'},
    {'country': 'Nauru', 'language': 'na'},
    {'country': 'Nepal', 'language': 'ne'},
    {'country': 'Netherlands', 'language': 'nl'},
    {'country': 'New Zealand', 'language': 'en'},
    {'country': 'Nicaragua', 'language': 'es'},
    {'country': 'Niger', 'language': 'fr'},
    {'country': 'Nigeria', 'language': 'en'},
    {'country': 'North Macedonia', 'language': 'mk'},
    {'country': 'Norway', 'language': 'no'},
    {'country': 'Oman', 'language': 'ar'},
    {'country': 'Pakistan', 'language': 'ur'},
    {'country': 'Palau', 'language': 'en'},
    {'country': 'Panama', 'language': 'es'},
    {'country': 'Papua New Guinea', 'language': 'en'},
    {'country': 'Paraguay', 'language': 'es'},
    {'country': 'Peru', 'language': 'es'},
    {'country': 'Philippines', 'language': 'tl'},
    {'country': 'Poland', 'language': 'pl'},
    {'country': 'Portugal', 'language': 'pt'},
    {'country': 'Qatar', 'language': 'ar'},
    {'country': 'Romania', 'language': 'ro'},
    {'country': 'Russia', 'language': 'ru'},
    {'country': 'Rwanda', 'language': 'rw'},
    {'country': 'Saint Kitts and Nevis', 'language': 'en'},
    {'country': 'Saint Lucia', 'language': 'en'},
    {'country': 'Saint Vincent and the Grenadines', 'language': 'en'},
    {'country': 'Samoa', 'language': 'sm'},
    {'country': 'San Marino', 'language': 'it'},
    {'country': 'Sao Tome and Principe', 'language': 'pt'},
    {'country': 'Saudi Arabia', 'language': 'ar'},
    {'country': 'Senegal', 'language': 'fr'},
    {'country': 'Serbia', 'language': 'sr'},
    {'country': 'Seychelles', 'language': 'fr'},
    {'country': 'Sierra Leone', 'language': 'en'},
    {'country': 'Singapore', 'language': 'en'},
    {'country': 'Slovakia', 'language': 'sk'},
    {'country': 'Slovenia', 'language': 'sl'},
    {'country': 'Solomon Islands', 'language': 'en'},
    {'country': 'Somalia', 'language': 'so'},
    {'country': 'South Africa', 'language': 'en'},
    {'country': 'South Sudan', 'language': 'en'},
    {'country': 'Spain', 'language': 'es'},
    {'country': 'Sri Lanka', 'language': 'si'},
    {'country': 'Sudan', 'language': 'ar'},
    {'country': 'Suriname', 'language': 'nl'},
    {'country': 'Sweden', 'language': 'sv'},
    {'country': 'Switzerland', 'language': 'de'},
    {'country': 'Syria', 'language': 'ar'},
    {'country': 'Taiwan', 'language': 'zh'},
    {'country': 'Tajikistan', 'language': 'tg'},
    {'country': 'Tanzania', 'language': 'sw'},
    {'country': 'Thailand', 'language': 'th'},
    {'country': 'Togo', 'language': 'fr'},
    {'country': 'Tonga', 'language': 'to'},
    {'country': 'Trinidad and Tobago', 'language': 'en'},
    {'country': 'Tunisia', 'language': 'ar'},
    {'country': 'Turkey', 'language': 'tr'},
    {'country': 'Turkmenistan', 'language': 'tk'},
    {'country': 'Tuvalu', 'language': 'en'},
    {'country': 'Uganda', 'language': 'sw'},
    {'country': 'Ukraine', 'language': 'uk'},
    {'country': 'United Arab Emirates', 'language': 'ar'},
    {'country': 'United Kingdom', 'language': 'en'},
    {'country': 'United States', 'language': 'en'},
    {'country': 'Uruguay', 'language': 'es'},
    {'country': 'Uzbekistan', 'language': 'uz'},
    {'country': 'Vanuatu', 'language': 'bi'},
    {'country': 'Vatican City', 'language': 'la'},
    {'country': 'Venezuela', 'language': 'es'},
    {'country': 'Vietnam', 'language': 'vi'},
    {'country': 'Yemen', 'language': 'ar'},
    {'country': 'Zambia', 'language': 'en'},
    {'country': 'Zimbabwe', 'language': 'en'}
]




