# Generated by Django 4.1.6 on 2023-05-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', max_length=200, null=True),
        ),
    ]
