# Generated by Django 4.1.6 on 2023-07-30 12:48

import custom_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.IntegerField(default=custom_user.models.generate_code),
        ),
    ]
