# Generated by Django 4.1.6 on 2023-10-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_user_issubscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='productDetails',
            field=models.JSONField(default={'payment': '', 'price': '', 'subscription': ''}),
        ),
    ]
