# Generated by Django 4.1.6 on 2023-10-31 20:37

import custom_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_user_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='productDetails',
            field=models.JSONField(default=custom_user.models.default_product_details),
        ),
    ]
