# Generated by Django 4.1.6 on 2023-10-31 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_alter_user_productdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='productDetails',
        ),
    ]
