# Generated by Django 4.1.6 on 2023-10-31 20:53

import custom_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_remove_user_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product_details',
            field=models.JSONField(default=custom_user.models.default_product_details),
        ),
    ]
