# Generated by Django 4.1.6 on 2024-04-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0009_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('businessOwner', 'businessOwner')], default='', max_length=20),
        ),
    ]
