# Generated by Django 4.1.6 on 2023-07-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(blank=True, default='', upload_to='profileImages/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
                ('occupation', models.CharField(default='', max_length=200)),
                ('languageOne', models.ImageField(blank=True, default='', upload_to='languages/')),
                ('languageTwo', models.ImageField(blank=True, default='', upload_to='languages/')),
                ('languageThree', models.ImageField(blank=True, default='', upload_to='languages/')),
                ('languageFour', models.ImageField(blank=True, default='', upload_to='languages/')),
            ],
        ),
    ]
