# Generated by Django 4.2.7 on 2024-11-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('profileImage', models.ImageField(blank=True, upload_to='profileImages/')),
                ('languages', models.JSONField(blank=True, default=list)),
                ('review', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('latitudeDelta', models.CharField(blank=True, max_length=50)),
                ('longitudeDelta', models.CharField(blank=True, max_length=50)),
                ('linkAddress', models.CharField(blank=True, max_length=50)),
                ('canton', models.CharField(choices=[('AG', 'Aargau'), ('AR', 'Appenzell Ausserrhoden'), ('AI', 'Appenzell Innerrhoden'), ('BL', 'Basel-Landschaft'), ('BS', 'Basel-Stadt'), ('BE', 'Bern'), ('FR', 'Fribourg'), ('GE', 'Geneva'), ('GL', 'Glarus'), ('GR', 'Graubünden'), ('JU', 'Jura'), ('LU', 'Lucerne'), ('NE', 'Neuchâtel'), ('NW', 'Nidwalden'), ('OW', 'Obwalden'), ('SG', 'St. Gallen'), ('SH', 'Schaffhausen'), ('SZ', 'Schwyz'), ('SO', 'Solothurn'), ('TG', 'Thurgau'), ('TI', 'Ticino'), ('UR', 'Uri'), ('VS', 'Valais'), ('VD', 'Vaud'), ('ZG', 'Zug'), ('ZH', 'Zurich')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImmigrationConsultant',
            fields=[
                ('professionals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.professionals')),
                ('occupation', models.CharField(default='', max_length=200)),
                ('licensed', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=200)),
                ('specialization', models.CharField(default='', max_length=500)),
                ('aboutMe', models.CharField(default='', max_length=500)),
            ],
            bases=('professionals.professionals',),
        ),
        migrations.CreateModel(
            name='InsuranceAgent',
            fields=[
                ('professionals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.professionals')),
                ('occupation', models.CharField(default='', max_length=200)),
                ('licensed', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=200)),
                ('specialization', models.CharField(default='', max_length=500)),
                ('aboutMe', models.CharField(default='', max_length=500)),
            ],
            bases=('professionals.professionals',),
        ),
    ]
