# Generated by Django 4.1.6 on 2023-12-28 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('profileImage', models.ImageField(blank=True, upload_to='profileImages/')),
                ('languages', models.JSONField(default=dict)),
                ('review', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceAgent',
            fields=[
                ('professionals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.professionals')),
                ('occupation', models.CharField(default='', max_length=200)),
                ('licensed', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=200)),
            ],
            bases=('professionals.professionals',),
        ),
    ]
