# Generated by Django 4.1.6 on 2023-12-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionals',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
