# Generated by Django 4.1.6 on 2023-12-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_alter_professionals_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceagent',
            name='aboutMe',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='insuranceagent',
            name='specialization',
            field=models.CharField(default='', max_length=500),
        ),
    ]
