# Generated by Django 4.1.6 on 2023-12-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_insuranceagent_aboutme_insuranceagent_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionals',
            name='latitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='professionals',
            name='latitudeDelta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='professionals',
            name='linkAddress',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='professionals',
            name='longitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='professionals',
            name='longitudeDelta',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
