# Generated by Django 4.1.6 on 2024-01-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_professionals_latitude_professionals_latitudedelta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationConsultant',
            fields=[
                ('professionals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.professionals')),
                ('occupation', models.CharField(default='', max_length=200)),
                ('licensed', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=200)),
                ('specialization', models.CharField(default='', max_length=500)),
                ('aboutMe', models.CharField(default='', max_length=500)),
            ],
            bases=('professionals.professionals',),
        ),
    ]
