# Generated by Django 4.1.6 on 2023-03-11 21:20

from django.db import migrations, models
import django.db.models.deletion
import healthcare.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0004_alter_city_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Health Care', max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=healthcare.models.get_image_path)),
                ('description', models.CharField(default='Medical insurance, finding a doctor, mental health', max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare', to='city.city')),
            ],
        ),
    ]
