# Generated by Django 4.1.6 on 2023-03-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcare',
            name='descriptionEs',
            field=models.CharField(default='Seguro médico, Encontrar un médico, Salud mental', max_length=200),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='descriptionFr',
            field=models.CharField(default='Assurance maladie, Trouver un médecin, Santé mentale', max_length=200),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='descriptionGe',
            field=models.CharField(default='Krankenversicherung, Einen Arzt finden, Psychische Gesundheit', max_length=200),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='descriptionGr',
            field=models.CharField(default='Ιατρική ασφάλεια, Εύρεση γιατρού, Ψυχική υγεία', max_length=200),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='descriptionIt',
            field=models.CharField(default='Assicurazione sanitaria, Trovare un medico, Salute mentale', max_length=200),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='titleEs',
            field=models.CharField(default='Atención médica', max_length=200),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='titleFr',
            field=models.CharField(default='Soins de santé', max_length=200),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='titleGe',
            field=models.CharField(default='Gesundheitsversorgung', max_length=200),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='titleGr',
            field=models.CharField(default='Φροντίδα & υγεία', max_length=200),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='titleIt',
            field=models.CharField(default='Assistenza sanitaria', max_length=200),
        ),
    ]
