# Generated by Django 4.1.6 on 2024-02-22 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='description',
            new_name='descriptions',
        ),
    ]
