# Generated by Django 4.1.6 on 2023-06-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='requiredDocuments',
        ),
    ]
