# Generated by Django 4.1.6 on 2023-06-26 22:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0002_remove_information_requireddocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='requiredDocuments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
