# Generated by Django 4.1.6 on 2023-05-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0002_city_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='city_images/'),
        ),
    ]
