# Generated by Django 4.1.6 on 2024-02-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0002_rename_description_information_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='descriptions',
        ),
    ]
