# Generated by Django 4.2.7 on 2024-11-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0003_remove_city_cantons_flag_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='table_image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='city',
            name='table_image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='information',
            name='table_image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='table_image',
            field=models.CharField(max_length=1000),
        ),
    ]
