# Generated by Django 4.1.6 on 2023-07-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0003_information_requireddocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=200),
        ),
    ]
