# Generated by Django 4.2.7 on 2024-11-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0004_alter_category_table_image_alter_city_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
