# Generated by Django 4.1.6 on 2023-09-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0004_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='city_images/'),
        ),
    ]
