# Generated by Django 4.1.6 on 2023-09-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='table_image',
            field=models.ImageField(blank=True, default='', upload_to='city_images/'),
        ),
        migrations.AddField(
            model_name='city',
            name='table_image',
            field=models.ImageField(blank=True, default='', upload_to='city_images/'),
        ),
        migrations.AddField(
            model_name='information',
            name='table_image',
            field=models.ImageField(blank=True, default='', upload_to='city_images/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='table_image',
            field=models.ImageField(blank=True, default='', upload_to='city_images/'),
        ),
    ]
