# Generated by Django 4.1.6 on 2023-05-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0005_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
