# Generated by Django 4.1.6 on 2023-10-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0006_category_table_image_city_table_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='canton_region',
            field=models.CharField(choices=[('DE', 'German'), ('IT', 'Italian'), ('FR', 'French')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='table_image',
            field=models.ImageField(blank=True, default='', upload_to='city_image/'),
        ),
    ]
