# Generated by Django 4.1.6 on 2023-12-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0008_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='table_image',
            field=models.ImageField(blank=True, default='', upload_to='city_images/'),
        ),
    ]
