# Generated by Django 4.1.6 on 2023-12-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0010_location_steps_information_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='steps',
            name='name',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
