# Generated by Django 4.1.6 on 2023-12-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0011_location_name_steps_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='stepOne',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='stepThree',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='stepTwo',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
