# Generated by Django 4.1.6 on 2023-12-03 20:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0012_alter_location_address_alter_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, default=list, size=None),
        ),
    ]
