# Generated by Django 4.1.6 on 2023-12-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0013_alter_steps_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='tip',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
