# Generated by Django 4.1.6 on 2023-12-04 20:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0014_steps_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='linksNames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, default=list, size=None),
        ),
    ]
