# Generated by Django 4.1.6 on 2023-12-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0015_steps_linksnames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='image',
        ),
        migrations.RemoveField(
            model_name='information',
            name='location',
        ),
        migrations.RemoveField(
            model_name='information',
            name='requiredDocuments',
        ),
        migrations.RemoveField(
            model_name='information',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='information',
            name='table_image',
        ),
        migrations.AddField(
            model_name='information',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
