# Generated by Django 4.1.6 on 2023-12-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0016_remove_information_image_remove_information_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='information',
            name='table_image',
            field=models.ImageField(blank=True, default='', upload_to='city_images/'),
        ),
    ]
