# Generated by Django 4.1.6 on 2024-01-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0017_information_image_information_table_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Steps',
        ),
    ]
