# Generated by Django 4.1.6 on 2024-01-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cities', '0018_delete_location_delete_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cantons_flag',
            field=models.ImageField(blank=True, default='', upload_to='cantons_icons/'),
        ),
    ]
