# Generated by Django 4.1.6 on 2023-03-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_regulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencypermit',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
