# Generated by Django 4.1.6 on 2023-03-10 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_alter_city_id'),
        ('law_regulations', '0002_residencypermit_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationLawsAndRegulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
            ],
        ),
        migrations.DeleteModel(
            name='ResidencyPermit',
        ),
    ]
