# Generated by Django 4.1.6 on 2023-03-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_regulations', '0003_immigrationlawsandregulations_delete_residencypermit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigrationlawsandregulations',
            name='title',
            field=models.CharField(default='Immigration laws and regulations', max_length=200),
        ),
    ]
