# Generated by Django 4.1.6 on 2023-03-11 19:37

from django.db import migrations, models
import law_regulations.models


class Migration(migrations.Migration):

    dependencies = [
        ('law_regulations', '0005_alter_immigrationlawsandregulations_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrationlawsandregulations',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=law_regulations.models.get_image_path),
        ),
    ]
