# Generated by Django 4.1.6 on 2023-03-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_regulations', '0006_immigrationlawsandregulations_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigrationlawsandregulations',
            name='title',
            field=models.CharField(default='Legal system & immigration', max_length=200),
        ),
    ]
