# Generated by Django 4.1.6 on 2023-03-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_regulations', '0007_alter_immigrationlawsandregulations_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrationlawsandregulations',
            name='description',
            field=models.CharField(default='Immigration and legal support,police', max_length=200),
        ),
    ]
