# Generated by Django 4.1.6 on 2023-03-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_regulations', '0008_immigrationlawsandregulations_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immigrationlawsandregulations',
            old_name='title',
            new_name='titleEn',
        ),
        migrations.AddField(
            model_name='immigrationlawsandregulations',
            name='titleEs',
            field=models.CharField(default='Sistema legal y migración', max_length=200),
        ),
    ]
