# Generated by Django 4.1.6 on 2023-03-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law_regulations', '0009_rename_title_immigrationlawsandregulations_titleen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immigrationlawsandregulations',
            old_name='titleEn',
            new_name='title',
        ),
    ]
