# Generated by Django 4.1.6 on 2023-03-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_regulations', '0010_rename_titleen_immigrationlawsandregulations_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrationlawsandregulations',
            name='titleFr',
            field=models.CharField(default='Système juridique et immigration', max_length=200),
        ),
        migrations.AddField(
            model_name='immigrationlawsandregulations',
            name='titleGe',
            field=models.CharField(default='Rechtssystem und Einwanderung', max_length=200),
        ),
        migrations.AddField(
            model_name='immigrationlawsandregulations',
            name='titleGr',
            field=models.CharField(default='Νομικό σύστημα και μετανάστευση', max_length=200),
        ),
        migrations.AddField(
            model_name='immigrationlawsandregulations',
            name='titleIt',
            field=models.CharField(default='Sistema legale e immigrazione', max_length=200),
        ),
    ]
