# Generated by Django 4.1.6 on 2023-03-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='descriptionEs',
            field=models.CharField(default='Encontrar un trabajo / Buscar empleo', max_length=200),
        ),
        migrations.AddField(
            model_name='employment',
            name='descriptionFr',
            field=models.CharField(default='Trouver un emploi', max_length=200),
        ),
        migrations.AddField(
            model_name='employment',
            name='descriptionGe',
            field=models.CharField(default='Einen Job finden', max_length=200),
        ),
        migrations.AddField(
            model_name='employment',
            name='descriptionGr',
            field=models.CharField(default='Εύρεση εργασίας', max_length=200),
        ),
        migrations.AddField(
            model_name='employment',
            name='descriptionIt',
            field=models.CharField(default='Trovare un lavoro', max_length=200),
        ),
        migrations.AddField(
            model_name='employment',
            name='titleEs',
            field=models.CharField(default='Empleo / Trabajo', max_length=200),
        ),
        migrations.AddField(
            model_name='employment',
            name='titleFr',
            field=models.CharField(default='Emploi / Travail', max_length=200),
        ),
        migrations.AddField(
            model_name='employment',
            name='titleGe',
            field=models.CharField(default='Beschäftigung / Arbeit', max_length=200),
        ),
        migrations.AddField(
            model_name='employment',
            name='titleGr',
            field=models.CharField(default='Εργασία / Απασχόληση', max_length=200),
        ),
        migrations.AddField(
            model_name='employment',
            name='titleIt',
            field=models.CharField(default='Impiego / Lavoro', max_length=200),
        ),
    ]
