# Generated by Django 4.1.6 on 2023-03-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_employment_descriptiones_employment_descriptionfr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='descriptionEs',
            field=models.CharField(default='Encontrar un trabajo / Buscar empleo,Trabajar en Suiza', max_length=200),
        ),
        migrations.AlterField(
            model_name='employment',
            name='descriptionFr',
            field=models.CharField(default='Trouver un emploi, Travailler en Suisse', max_length=200),
        ),
        migrations.AlterField(
            model_name='employment',
            name='descriptionGe',
            field=models.CharField(default='Einen Job finden, Arbeiten in der Schweiz', max_length=200),
        ),
        migrations.AlterField(
            model_name='employment',
            name='descriptionGr',
            field=models.CharField(default='Εύρεση εργασίας, Εργασία στην Ελβετία', max_length=200),
        ),
        migrations.AlterField(
            model_name='employment',
            name='descriptionIt',
            field=models.CharField(default='Trovare un lavoro, Lavorare in Svizzera', max_length=200),
        ),
    ]
