# Generated by Django 4.1.6 on 2023-06-26 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.IntegerField(default=registration.models.generate_code)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=20)),
                ('selectedCountry', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
