# Generated by Django 4.1.6 on 2023-03-04 16:12

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='verification_code',
            field=models.IntegerField(default=registration.models.generate_code),
        ),
    ]
