# Generated by Django 4.1.6 on 2023-07-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translatedImage', models.ImageField(upload_to='translatedImages/')),
            ],
        ),
    ]
