# Generated by Django 4.1.6 on 2023-03-11 20:38

from django.db import migrations, models
import django.db.models.deletion
import moneybanking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0004_alter_city_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyBanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Money & banking', max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=moneybanking.models.get_image_path)),
                ('description', models.CharField(default='Opening a back account,filing taxes', max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Moneyandbanking', to='city.city')),
            ],
        ),
    ]
