# Generated by Django 4.1.6 on 2023-03-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_alter_city_id'),
        ('moneybanking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybanking',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Moneybanking', to='city.city'),
        ),
    ]
