# Generated by Django 4.1.6 on 2023-03-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybanking', '0003_alter_moneybanking_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybanking',
            name='description',
            field=models.CharField(default='Opening a bank account,filing taxes', max_length=200),
        ),
    ]
