# Generated by Django 4.1.6 on 2023-03-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybanking', '0004_alter_moneybanking_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneybanking',
            name='descriptionEs',
            field=models.CharField(default='Apertura de una cuenta bancaria,Presentación de impuestos', max_length=200),
        ),
        migrations.AddField(
            model_name='moneybanking',
            name='descriptionFr',
            field=models.CharField(default='Ouverture d un compte bancaire,Déclaration fiscale', max_length=200),
        ),
        migrations.AddField(
            model_name='moneybanking',
            name='descriptionGe',
            field=models.CharField(default='Eröffnung eines Bankkontos,Einreichung der Steuererklärung', max_length=200),
        ),
        migrations.AddField(
            model_name='moneybanking',
            name='descriptionGr',
            field=models.CharField(default='Άνοιγμα τραπεζικού λογαριασμού,Υποβολή φορολογικής δήλωσης', max_length=200),
        ),
        migrations.AddField(
            model_name='moneybanking',
            name='descriptionIt',
            field=models.CharField(default='Apertura di un conto bancario,Presentazione della dichiarazione dei redditi', max_length=200),
        ),
        migrations.AddField(
            model_name='moneybanking',
            name='titleES',
            field=models.CharField(default='Dinero y banca', max_length=200),
        ),
        migrations.AddField(
            model_name='moneybanking',
            name='titleFr',
            field=models.CharField(default='Argent et banque', max_length=200),
        ),
        migrations.AddField(
            model_name='moneybanking',
            name='titleGe',
            field=models.CharField(default='Geld und Bankwesen', max_length=200),
        ),
        migrations.AddField(
            model_name='moneybanking',
            name='titleGr',
            field=models.CharField(default='Χρήματα και τραπεζικό σύστημα', max_length=200),
        ),
        migrations.AddField(
            model_name='moneybanking',
            name='titleIt',
            field=models.CharField(default='Moneta e banca', max_length=200),
        ),
    ]
