# Generated by Django 4.1.6 on 2023-03-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybanking', '0005_moneybanking_descriptiones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneybanking',
            old_name='titleES',
            new_name='titleEs',
        ),
    ]
