# Generated by Django 4.1.6 on 2023-03-11 22:00

from django.db import migrations, models
import django.db.models.deletion
import housing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0004_alter_city_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Housing', max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=housing.models.get_image_path)),
                ('description', models.CharField(default='Finding a place to rent or buy', max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='city.city')),
            ],
        ),
    ]
