# Generated by Django 4.1.6 on 2023-03-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='descriptionEs',
            field=models.CharField(default='Encontrar un lugar para alquilar o comprar', max_length=200),
        ),
        migrations.AddField(
            model_name='housing',
            name='descriptionFr',
            field=models.CharField(default='Trouver un lieu à louer ou acheter', max_length=200),
        ),
        migrations.AddField(
            model_name='housing',
            name='descriptionGe',
            field=models.CharField(default='Eine Wohnung oder ein Haus mieten oder kaufen', max_length=200),
        ),
        migrations.AddField(
            model_name='housing',
            name='descriptionGr',
            field=models.CharField(default='Εύρεση καταλύματος προς ενοικίαση ή αγορά ', max_length=200),
        ),
        migrations.AddField(
            model_name='housing',
            name='descriptionIt',
            field=models.CharField(default='Trovare un posto dove affittare o comprare', max_length=200),
        ),
        migrations.AddField(
            model_name='housing',
            name='titleEs',
            field=models.CharField(default='Vivienda / Alojamiento', max_length=200),
        ),
        migrations.AddField(
            model_name='housing',
            name='titleFr',
            field=models.CharField(default='Logement / Hébergement', max_length=200),
        ),
        migrations.AddField(
            model_name='housing',
            name='titleGe',
            field=models.CharField(default='Wohnen / Unterkunft', max_length=200),
        ),
        migrations.AddField(
            model_name='housing',
            name='titleGr',
            field=models.CharField(default='Κατοικία', max_length=200),
        ),
        migrations.AddField(
            model_name='housing',
            name='titleIt',
            field=models.CharField(default='Alloggio / Abitazione', max_length=200),
        ),
    ]
